# Generated by Django 5.2.17 on 2026-09-30 10:34

import apps.projection.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                (
                    "couleur_fond",
                    models.CharField(
                        default="#000000",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9a-fA-F]{6}$", "Couleur au format #RRGGBB."
                            )
                        ],
                        verbose_name="couleur de fond",
                    ),
                ),
                (
                    "image_fond",
                    models.ImageField(
                        blank=True,
                        help_text="Optionnelle, étirée sur toute la diapo.",
                        upload_to="themes/",
                        validators=[apps.projection.models.image_legere],
                        verbose_name="image de fond",
                    ),
                ),
                (
                    "couleur_texte",
                    models.CharField(
                        default="#ffffff",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9a-fA-F]{6}$", "Couleur au format #RRGGBB."
                            )
                        ],
                        verbose_name="couleur du texte",
                    ),
                ),
                (
                    "police",
                    models.CharField(
                        choices=[
                            ("Calibri", "Calibri"),
                            ("Arial", "Arial"),
                            ("Segoe UI", "Segoe UI"),
                            ("Verdana", "Verdana"),
                            ("Tahoma", "Tahoma"),
                            ("Trebuchet MS", "Trebuchet MS"),
                            ("Century Gothic", "Century Gothic"),
                            ("Georgia", "Georgia"),
                            ("Times New Roman", "Times New Roman"),
                        ],
                        default="Calibri",
                        max_length=40,
                        verbose_name="police des paroles",
                    ),
                ),
                (
                    "police_titres",
                    models.CharField(
                        choices=[
                            ("Calibri", "Calibri"),
                            ("Arial", "Arial"),
                            ("Segoe UI", "Segoe UI"),
                            ("Verdana", "Verdana"),
                            ("Tahoma", "Tahoma"),
                            ("Trebuchet MS", "Trebuchet MS"),
                            ("Century Gothic", "Century Gothic"),
                            ("Georgia", "Georgia"),
                            ("Times New Roman", "Times New Roman"),
                        ],
                        default="Georgia",
                        max_length=40,
                        verbose_name="police des titres",
                    ),
                ),
                (
                    "gras",
                    models.BooleanField(default=True, verbose_name="paroles en gras"),
                ),
                (
                    "taille_paroles",
                    models.PositiveSmallIntegerField(
                        default=54,
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(120),
                        ],
                        verbose_name="taille des paroles (pt)",
                    ),
                ),
                (
                    "taille_titre",
                    models.PositiveSmallIntegerField(
                        default=32,
                        validators=[
                            django.core.validators.MinValueValidator(14),
                            django.core.validators.MaxValueValidator(96),
                        ],
                        verbose_name="taille des titres (pt)",
                    ),
                ),
                (
                    "titres_majuscules",
                    models.BooleanField(
                        default=True, verbose_name="titres en majuscules"
                    ),
                ),
                (
                    "couleur_bandeau",
                    models.CharField(
                        default="#8f8f8f",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9a-fA-F]{6}$", "Couleur au format #RRGGBB."
                            )
                        ],
                        verbose_name="couleur du bandeau de bienvenue",
                    ),
                ),
                (
                    "image_bienvenue",
                    models.ImageField(
                        blank=True,
                        help_text="Optionnelle : remplace toute la diapo de bienvenue (texte compris).",
                        upload_to="themes/",
                        validators=[apps.projection.models.image_legere],
                        verbose_name="image de bienvenue",
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
            ],
            options={
                "verbose_name": "thème",
                "verbose_name_plural": "thèmes",
                "ordering": ["nom"],
            },
        ),
    ]
