# Generated by Django 5.2.17 on 2026-09-30 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("auteur", models.CharField(blank=True, max_length=200)),
                ("langue", models.CharField(default="Français", max_length=50)),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Séparés par des virgules, par exemple : adoration, louange, Noël",
                        max_length=300,
                    ),
                ),
                ("recherche", models.TextField(blank=True, editable=False)),
                (
                    "date_ajout",
                    models.DateTimeField(auto_now_add=True, verbose_name="ajouté le"),
                ),
                (
                    "date_modification",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chants_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "chant",
                "verbose_name_plural": "chants",
                "ordering": ["titre"],
            },
        ),
        migrations.CreateModel(
            name="Couplet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordre", models.PositiveSmallIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("couplet", "Couplet"),
                            ("refrain", "Refrain"),
                            ("pont", "Pont"),
                        ],
                        default="couplet",
                        max_length=10,
                    ),
                ),
                (
                    "numero",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Numéro affiché devant le couplet",
                        null=True,
                        verbose_name="numéro",
                    ),
                ),
                ("texte", models.TextField()),
                (
                    "chant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="couplets",
                        to="chants.chant",
                    ),
                ),
            ],
            options={
                "verbose_name": "couplet",
                "verbose_name_plural": "couplets",
                "ordering": ["chant", "ordre"],
            },
        ),
    ]
