# Generated by Django 5.2.17 on 2026-09-30 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chants", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="couplet",
            options={
                "ordering": ["chant_id", "ordre"],
                "verbose_name": "couplet",
                "verbose_name_plural": "couplets",
            },
        ),
    ]
