# Generated by Django 5.2.17 on 2026-09-30 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chants", "0002_alter_couplet_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chant",
            options={
                "ordering": ["recherche", "pk"],
                "verbose_name": "chant",
                "verbose_name_plural": "chants",
            },
        ),
    ]
