# Generated by Django 5.2.17 on 2026-10-05 04:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chants", "0006_delete_couplet"),
    ]

    operations = [
        migrations.AddField(
            model_name="diapochant",
            name="police",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="diapochant",
            name="taille",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(8),
                    django.core.validators.MaxValueValidator(200),
                ],
                verbose_name="taille du texte (pt)",
            ),
        ),
    ]
