# Generated by Django 5.2.17 on 2026-09-30 04:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chants", "0002_alter_couplet_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Culte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("date", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[("brouillon", "Brouillon"), ("pret", "Prêt")],
                        default="brouillon",
                        max_length=10,
                    ),
                ),
                (
                    "texte_bienvenue",
                    models.TextField(
                        blank=True,
                        default="Bienvenus dans la maison du Seigneur",
                        help_text="Première diapo du culte. Laisser vide pour ne pas l'afficher.",
                        verbose_name="texte de bienvenue",
                    ),
                ),
                (
                    "lignes_par_diapo",
                    models.PositiveSmallIntegerField(
                        default=4,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="lignes par diapo",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "date_modification",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cultes_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "culte",
                "verbose_name_plural": "cultes",
                "ordering": ["-date", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="ElementCulte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordre", models.PositiveIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[("chant", "Chant"), ("texte", "Texte libre")],
                        max_length=10,
                    ),
                ),
                ("moment", models.CharField(blank=True, max_length=100)),
                (
                    "repeter_refrain",
                    models.BooleanField(
                        default=True, verbose_name="répéter le refrain"
                    ),
                ),
                ("masque", models.BooleanField(default=False, verbose_name="masqué")),
                ("titre", models.CharField(blank=True, max_length=200)),
                ("contenu", models.TextField(blank=True)),
                (
                    "chant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="utilisations",
                        to="chants.chant",
                    ),
                ),
                (
                    "culte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elements",
                        to="cultes.culte",
                    ),
                ),
            ],
            options={
                "verbose_name": "élément du culte",
                "verbose_name_plural": "éléments du culte",
                "ordering": ["ordre", "pk"],
            },
        ),
    ]
