# Generated by Django 5.2.17 on 2026-09-30 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cultes", "0001_initial"),
        ("projection", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="culte",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                help_text="Vide : thème « Classique ».",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cultes",
                to="projection.theme",
                verbose_name="thème",
            ),
        ),
        migrations.AlterField(
            model_name="culte",
            name="texte_bienvenue",
            field=models.TextField(
                blank=True,
                default="Bienvenus\ndans la\nmaison du Seigneur",
                help_text="Première diapo du culte. Laisser vide pour ne pas l'afficher.",
                verbose_name="texte de bienvenue",
            ),
        ),
    ]
