# Generated by Django 5.2.17 on 2026-10-05 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cultes", "0002_culte_theme_alter_culte_texte_bienvenue"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elementculte",
            name="repeter_refrain",
        ),
    ]
